# values.yaml
image:
  repository: ubuntu
  tag: latest
  pullPolicy: IfNotPresent

command:
  - "sleep"
  - "infinity"  # Keeps the container running forever

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}