# templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "juju-client.fullname" . }}-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "juju-client.fullname" . }}-cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "juju-client.fullname" . }}-sa
    namespace: {{ .Release.Namespace }}