# templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "juju-client.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi