# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "juju-client.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ include "juju-client.fullname" . }}-sa
type: kubernetes.io/service-account-token