# templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "juju-client.fullname" . }}-sa
  namespace: {{ .Release.Namespace }}
secrets:
- name: juju-client-secret #link the secret to SA